export const GET_DATA_DETAIL = 'GET_DATA_DETAIL';
export const GET_DATA_DETAIL_SUCCESS = 'GET_DATA_DETAIL_SUCCESS';
export const GET_DATA_DETAIL_ERROR = 'GET_DATA_DETAIL_ERROR';
export const CHANGE_QUATITY = 'CHANGE_QUATITY';
export const INCREASE_QUATITY = 'INCREASE_QUATITY';
export const DECREASE_QUATITY = 'DECREASE_QUATITY';
