export const FILTER_DATA_CATEGORY = 'FILTER_DATA_CATEGORY';
export const FILTER_DATA_CATEGORY_SUCCESS = 'FILTER_DATA_CATEGORY_SUCCESS';
export const FILTER_DATA_CATEGORY_ERROR = 'FILTER_DATA_CATEGORY_ERROR';
export const SEARCH_DATA_CATEGORY = 'SEARCH_DATA_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_ERROR = 'GET_ALL_CATEGORY_ERROR';
export const LOADING_DATA_LIST_CATEGORY = 'LOADING_DATA_LIST_CATEGORY';
